services:
    mysql:
        image: mysql:8.0
        container_name: mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: weatherdb
            MYSQL_USER: "toanclient" # sample is the name of user
            MYSQL_PASSWORD: "ductoan0712" # password for sample
        ports:
            - "3306:3306"
        networks:
            - springboot-network
        volumes:
            - "./docker/db/data:/var/lib/mysql"

networks:
    springboot-network:
        driver: bridge
